version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      dotnet:
        patterns: ["Microsoft.*", "System.*"]
      tests:
        patterns: ["xunit*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
